### ISSUE TITLE
Increasing GHG footprint over time for electricity in RCP scenarios

### ISSUE THREAD

**Issue by mkvdhulst** [polca/premise#157]
Dear all,

When comparing results for the GHG footprint of 1 kWh of medium voltage electricity (ENTSO-E) between two versions of premise, my colleague Anne Ottenbros noticed a discrepancy. Using `v.1.5.0-beta3`, we found a continual decline in GHG footprint for the RCP scenarios:

![premise150b3](https://github.com/polca/premise/assets/72611056/c2df3b26-75a0-4eea-976e-cef7a47f4f4b)

whereas using `v.1.8.1` we see the GHG footprint first decreases and then increases for the RCP scenarios:

![premise181](https://github.com/polca/premise/assets/72611056/7246864c-5b62-4ac6-a1b9-ea056946a893)

We would expect the continual decline in GHG footprint, and therefore looked into the changes implemented between both versions to understand why the later version gives this unexpected result. We compared versions on GitHub, but could not identify any reason for this discrepancy. There are a total of 261 commits and 137 file changes between these versions, so there's a good chance we missed something. 

- **Are we correct in assuming the GHG footprint should continually decline in the RCP scenarios?** 
- **If not, what explanation for the increase in GHG footprint have we overlooked?**
- **If the GHG footprint should indeed decline, are the divergent results from `v.1.8.1` a known issue?**
- **If the divergent results are a known issue, has this been resolved in the most recent version?** 

We saw that the latest `v.2.0.0` lists "Fix issue with CCS in IMAGE scenarios" as a new feature, which was implemented in version `v.1.8.2-dev3`. However, as far as we could tell from comparing `v.1.8.2-dev3` and `v.1.8.2-dev2`, these fixes relate to fuels and not electricity. Would updating to the latest version nonetheless resolve our issue?

_Note: We use the climate change category from ReCiPe 2016. The difference in names of the methods is simply because the results from the two figures were created in two different projects where the adjustment to ReCiPe were conducted in different ways. In both cases, we have added CFs for biogenic carbon and hydrogen and have adjusted CFs for biogenic methane, as is done with `premise_gwp`. The LCIA methods should therefore be identical and cannot be at the root of this difference in results._

**Comment by romainsacchi** [comment]
Hi @mkvdhulst 
Yes, there have been a few hiccups with v.1.8.
Essentially, the dynamics in results that you show with v.1.5 is correct, although the absolute values are a bit wrong and were corrected in v.2.
So I suggest updating to v.2.0.2, which has significantly corrected and improved upon v.1.5 and v.1.8.
This is what it'll give you:

<img width="762" alt="Screenshot 2024-03-15 at 11 46 05" src="https://github.com/polca/premise/assets/22473067/7c8216f7-b595-4745-b19d-b5312ad9e134">

The BASE scenario (no climate mitigation) is meant to go up in the future. This is a bit surprising, but it fits the IMAGE scenarios, as there is a renewables roll-back because the carbon price is too weak. Hence, BASE is not really a BAU scenario, but rather pessimistic.

**Comment by romainsacchi** [comment]
I'll close this issue but do re-open it if needed.

**Comment by mkvdhulst** [comment]
Thank you for the response. I have tried the 2.0.2 version and it indeed gave results in line with expectation, so the issue can remain closed.
