### ISSUE TITLE
geomatcher - add an option to choose the model resolution

### ISSUE THREAD

**Issue by kais-siala** [polca/premise#33]
Currently, premise loads the geomatcher from wurst, which already has predefined model regions for IMAGE and REMIND.
However, there are now two possible spatial resolutions for REMIND, and we could expect that there would be more possibilities in the future.
How should we deal with that?
1) we could edit wurst and add the option there
2) we could shift the addition of the regions to premise instead of doing it in wurst. This means that wurst/wurst/geo.py gets a bit shorter, and we only add the region definitions in premise/premise/geomap.py

I tried leaving wurst as it is, and adding the new region definitions to premise, but I got warnings about duplicate definitions.
How do you think we should proceed?

**Comment by tngTUDOR** [comment]
Hi,
Here's my point of view.

It seems to me that `premise` uses wurst for some "basic" tasks (like _geomatching_). This allows `premise` to be focused on `modelling related` tasks.

With this in mind, I would suggest to update `wurst` to be able to handle the new resolution levels of REMIND, so that not only `premise`, but other tools can rely on `wurst`. In this case, the most important modifications would be done at `wurst` and premise would need to update a the different calls to `wurst` related to geomatching. 
On the other hand, this requires significant modifications at two places (`wurst` + `premise`), and depending on the urgency this might not be the quickest option.

**Comment by romainsacchi** [comment]
I concur with @tngTUDOR , the topology definitions should be added within `wurst`, as we did when we added topology definitions for REMIND (only those of IMAGE were present until then).

**Comment by kais-siala** [comment]
Yes I created a pull request in wurst following your advice. Thank you both.

**Comment by romainsacchi** [comment]
Thanks, I merged your PR. I will ask Chris to upload the change to Pypi.
